### ISSUE TITLE
EventBus refactoring

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#127]
The event bus must be refactored. There are several points that are currently just wrong / bad:
- The event bus should handle events for the current dolphin context directly (see #109 )
- Currently it's very hard to define tests for the event bus (see #64 )
- A interrupt (long polling) should only interrupt the current dolphin context
- The current implementation of the event bus can't be used for controller testing
- Add a configurable timeout for the event bus (for the long polling)
- The event bus must support a distributed event bus (like hazelcast http://hazelcast.org/use-cases/messaging/)
- define some (private) API endpoints that can be used for monitoring of the event bus

**Comment by Dierk** [comment]
Why not just using the OD event bus?

**Comment by hendrikebbers** [comment]
general event bus definition found by @andreashenle : https://github.com/google/guava/wiki/EventBusExplained

**Comment by hendrikebbers** [comment]
see #269
