### ISSUE TITLE
Server fails to start with new version

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#138]
We are currently using version 0.8.2 of the Dolphin Platform. I tried to switch to a snapshot version and with that the server fails to start.

The problem appears to be in DolphinPlatformSpringBootstrap. The method createEventBus() is called before onStartup(), which means that bootstrap.dolphinContextHandler has not been set yet and we get an NPE.

**Comment by hendrikebbers** [comment]
I created the "Fix-Event-Bus-Initialization" branch that should fix this problem. Since the branches depends on pull request #131 I haven't create a pull request for now. Will do it once #131 is merged.
@netopyr can you please test if the Branch is working with your project?

**Comment by hendrikebbers** [comment]
Created pull request #145 that should solve this problem.
