### ISSUE TITLE
Thread handling in remoting client

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#181]
Currently a disconnect that is send from JFX client may not be happen since the thread that handles the communication in the client is no daemon thread.

In the ClientContextImpl we have this:

```
public synchronized CompletableFuture<Void> disconnect() {
       ...
        Executors.newSingleThreadExecutor().execute(() -> {           
       dolphinCommandHandler.invokeDolphinCommand(...).handle((v, t) -> {
                       // ON DESTROY  <<---- THIS MIGHT NOT HAPPEN
                    });
                }
        );
        return result;
    }

```
If we simply call this when a JFX application is closed (stop() method in Application) the DESTROY command won't be send to the server since the application exits before the command will be send and the internal remoting thread will be killed before it sends the command.

In addition the callback that should be handled once the command was handled is never called since it will be called on the ui thread. this thread is already dead. Maybe we can define an additional method in the remoting that handles the callback in a background (daemon) thread.

**Comment by aalmiray** [comment]
Another option would be to make sure all dolphin requests/responses are handled in a Dolphin thread. Currently that thread is the UI thread.

**Comment by hendrikebbers** [comment]
By doing so value change event of the properties would happen outside of the UI thread by default. But we could provide a specific client implementation for the Property interface that internally uses the runLater to call the listeners.
