### ISSUE TITLE
Clear context when initClientContext is called

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#182]
Currently we do not really clear the representation of a ClientContext in the server when initClientContext is invoked, but part of the objects are reused. This causes issues, because the client expects a clean state after calling initClientContext.

**Comment by hendrikebbers** [comment]
I think that is not the right solution. Currently a ClientContext is bound to a HttpSession. Once we introduce the unique client ID in request / response a ClientContext would not be reused. Even a browser refresh would create a new client context is that case.

**Comment by hendrikebbers** [comment]
see #50
