### ISSUE TITLE
Providing the http layer of DP as public API

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#187]
We have several needs for the HTTP layer of DP:
- Configuration of the http layer by defining SSL, Cookies or Keystore
- Modification of all requests by adding custom headers (like for JWT)
- doing custom http request by using the http layer of DP. By doing so you can do http requests in the same session. This is needed if you want to upload or download a file for example.

Currently DP uses Apache Http client internally but I think it's not the best idea to continue with this dependency and provide the http client as public API. JAX-RS 2.0 provides a client API (javax.ws.rs.client.*) that is more or less a standard and we should provide this API as public API.

I currently now 2 implementations of the JAX-RS 2.0 client API:
- Jersey
- RESTeasy

Jersey has to many dependencies why I would choose RESTeasy as dependency for the DP client. In addition RestEasy uses the Apache HTTP client lib internally. If we internally only work against the JAX-RS API it will be quite easy for a developer to change the implementation and provide a custom one. JAX-RS will internally use SPI to find an implementation . In addition the ClientContextFactory should provide an addition method in that a developer can pass a javax.ws.rs.client.ClientBuilder instance. By doing so it will be quite easy to configure the HTTP client for the Dolphin Platform. Instead of providing the Apache HttpClient in the ClientContext we should provide the JAX-RS javax.ws.rs.client.Client

I think by doing this change a developer can easily configure the http layer of the Dolphin Platform and use it for custom http requests.

**Comment by hendrikebbers** [comment]
@netopyr @aalmiray any feedback?

**Comment by aalmiray** [comment]
http://square.github.io/okhttp/ would give us access to HTTP on the client side

**Comment by hendrikebbers** [comment]
Until now we use UrlHttpConnection. This is part of the JRE and can be used in Android, too. I think that all use cases can be handled by the basic API.
