### ISSUE TITLE
Slow down HttpTransmitter when connection is down

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#197]
When the connection is not available, the HttpTransmitter tries to keep sending commands with full speed. It should be smarter and slow down after e.g. 3 failed attempts to send something and go back to the normal mode when the connection is back.

**Comment by hendrikebbers** [comment]
Discussed this with @netopyr and we think a timeout should be used here:

if the client is disconnected a "disconnected" flag should be set
While the "disconnected" flag is set the HTTP calls should happen in a timeout (maybe a request all 5 seconds or so)
Once a request si successful the "disconnected" flag should be reseted

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform-js/pull/16
