### ISSUE TITLE
Provide meta-information of properties

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#198]
We need to access some meta-information about Dolphin properties. For a start the owning bean and the property name would be sufficient.

**Comment by hendrikebbers** [comment]
Sounds good :)
I already created a similar API for the Garbage Collection. If we directly provide metadata for properties and lists I can use it in GC, too.

**Comment by hendrikebbers** [comment]
This issue was moved to rico-project/rico#3
