### ISSUE TITLE
Additional methods for ObservableList to add elements

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#20]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
The JavaFX ObservableList interface adds some nice methods to the list interface like 
`add(int index, E... elements)` that we should add to out ObservableList interface and implementation.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by PlatanoBailando** [comment]
I'll try working on this guy.

**Comment by PlatanoBailando** [comment]
Though, I am a bit puzzled, as there is no method with a signature of `add(int index, E... elements) ` in JavaFX ObservableList: https://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableList.html

**Comment by hendrikebbers** [comment]
lol, you are right. So the methods that are part of the JFX interface should be added ;)

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform/pull/682
