### ISSUE TITLE
unclear documentation on garbage collection

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#232]
> The Dolphin Platform contains a garbage collection on the server that will automatically remove all bean instances from the remoting layer that aren’t referenced anymore by other beans. Currently the garbage collection is an experimental feature and it’s active by default. If you want to use the garbage collection you need to activate it in the dolphin.properties file.

This description is contradicting: "active by default" vs. "you need to activate it". And it is missing the vital information of the property name as well as allowed values.

**Comment by hendrikebbers** [comment]
fixed documentation in master branch
