### ISSUE TITLE
Support for the new Java Time API / ConverterFactory

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#258]
Thank you for this great work!

Two things would be helpful:
- Support for the new Java Time API
- or even better would be a way to set a ConverterFactory or similar 

In case of a ConverterFactory one could easily set up own converters if a specific API is not supported.

**Comment by hendrikebbers** [comment]
Thanks for the input. We had the same idea, too. See #98 #55 and #75

**Comment by hendrikebbers** [comment]
PR: #263

**Comment by hendrikebbers** [comment]
PR is merged
