### ISSUE TITLE
Modelle nur auf Client-Seite

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#26]
Open Dolphin erlaubt es, dass durch ein Send Modelle an den Client geschickt werden die nicht im Server gehalten werden. Dies ist z.B. sehr sinnvoll für Suchergebnisse etc. die man eigentlich nicht mehr im Server benötigt und hier nur Speicherplatz wegnehmen würden.

**Comment by hendrikebbers** [comment]
Duplicate of https://github.com/canoo/dolphin-platform/issues/344
