### ISSUE TITLE
Warning when trying to inject DolphinSession in session-scoped component

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#266]
Recently I injected a DolphinSession in a session-scoped component in our Spring Boot application. This was obviously a bug. Unfortunately there was no Exception or at least a warning. Would be nice if there could be some kind of notification, if a user does this.

**Comment by hendrikebbers** [comment]
In Spring you will not get an exception if you inject a request scoped bean in a session scoped bean. Spring do not provide an API to define injection hierarchies that are not allowed. Based on this I think that we can close this issue.

On JavaEE everything is fine since proxies are always used.
