### ISSUE TITLE
@NotNull support for Properties

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#27]
Wenn man z.B. eine JPA basierte Anwendung hat, dann hat man in den entities in der Regel:

@Column
private boolean active;

Will man das z.B. in der View darstellen, dann hat man sowas:

Property<Boolean> active;

Beim hin & her konvertieren muss man nun aber immer auf null values achten und es kommt zu blöden exceptions. Wenn wir das ganze aber in der Kommunikation checken würden (durch @NotNull) dann könnte man vernünftige Meldungen / Exceptions ausgeben.

**Comment by hendrikebbers** [comment]
Java Bean Validation can be added to DP and properties can be validated. This is part of a a Pull request and will be implemented in 0.8
