### ISSUE TITLE
provide CHANGELOG

### ISSUE THREAD

**Issue by madmas** [canoo/dolphin-platform#274]
The dolphin-platform does not provide a CHANGELOG.

As we encountered just a breaking change due to a changed package structure, I suggest to add and maintain a CHANGELOG to outline changes, esp. breaking one, between releases.

**Comment by hendrikebbers** [comment]
@madmas any idea how this can be handled the best way? Simply add it to the asciidoc documentation?

**Comment by madmas** [comment]
I'd suggest to maintin a separate file (most easy to find and refer to) and include that into the documentation. AsciiDoctor is of course a great candidate for that :)

**Comment by hendrikebbers** [comment]
see #276
