### ISSUE TITLE
Add javascript promise for disconnect in dolphin-platform-js

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#280]
The dolphin-polymer.js file has a disconnect-function.

ClientContext.prototype.disconnect = function () {
    // TODO: Implement ClientContext.disconnect [DP-46]
    var self = this;
    this.dolphin.stopPushListening();
    this._controllerManager.destroy().then(function () {
        console.log('destroyed');
        self._connector.invoke(DISCONNECT_COMMAND_NAME);
        self.dolphin = null;
        self.beanManager = null;
        self._controllerManager = null;
        self._connector = null;
    });
};

To implement the logout mechanism properly in Icos we need to have that code executed in a promise so that we can react after the disconnection.

**Comment by kunsingh** [comment]
There is no dolphin-polymer.js file in polymer project. We have dolphin-polymer-api.js, but here we don't disconnect() method.  We have disconnect method in clientcontext.js of 'dolphin-platform-js'.
I am suppose to add promise to 'dolphin-platform-js' -> clientcontext.js? right!

**Comment by hendrikebbers** [comment]
I think so. @kunsingh You did this, right? Can we close this issue?

**Comment by kunsingh** [comment]
NO....so this change is remaining.....I had asked you what to resolve. I found how to resolve without any promise on js side. Only question is that- this change is suppose to be done in js project not in polymer ...right?

**Comment by hendrikebbers** [comment]
yes, I think you are right

**Comment by kunsingh** [comment]
ok...I will make the required changes.

**Comment by hendrikebbers** [comment]
See https://github.com/canoo/dolphin-platform-js/pull/9
