### ISSUE TITLE
Client API should not use Java 8 classes

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#298]
Currently we use CompleteableFuture. Since this is working with the JavaFX client API and Android we should remove it to be really compatible to Java 7

**Comment by aalmiray** [comment]
JDeferred works on Android and Java6 onwards

**Comment by hendrikebbers** [comment]
Yes! I would prefer using JDeferred or provide a small internal API based on Java7 (to avoid dependencies)

**Comment by aalmiray** [comment]
Reinventing the wheel because a minimum dependency policy only makes sense if the target platform has strict limits regarding memory and deployment size IMHO.
