### ISSUE TITLE
Licence Headers missing in AngularJS project

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#306]
See https://www.npmjs.com/package/gulp-header-license for example. License file can be found in DP main repository

**Comment by kunsingh** [comment]
As I can see we already have license header in dolphin-platform-js project source code. We can add license header to Polymer and Angular source code.
Do we really need license header for minified js files?

**Comment by hendrikebbers** [comment]
I don't know if we need them for minified files. @aalmiray @netopyr maybe you have an idea?

**Comment by netopyr** [comment]
AFAIK license headers are never required, only recommended.

**Comment by kunsingh** [comment]
Done.
