### ISSUE TITLE
Change Links in dolphin-platform.io

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#316]
All links for documentation and tutorial should link to github documentation

**Comment by hendrikebbers** [comment]
In addition there are some broken links on the website.

In general we should forward all links to github / documentation at github

**Comment by timo0** [comment]
Should we forward dolphin-platform.io directly to canoo.github.io/dolphin-platform until we have the new Website?

**Comment by hendrikebbers** [comment]
Discussed this already with Dirk but he don't want it.

**Comment by hendrikebbers** [comment]
It looks like Google indexes sub pages of the webpage that we did not use anymore. Maybe we should redirect the pages to GitHub and remove the old HTMl pages.

**Comment by hendrikebbers** [comment]
Comment:
Hendrik, wenn ich auf http://www.dolphin-platform.io/documentation/getting-started.html auf den Button "VIEW ON GITHUB" klicke, dann wird die URL http://www.dolphin-platform.io/documentation/register.html benutzt und die Seite gibt es nicht

**Comment by timo0** [comment]
Pull Request is done, waiting for update on the webserver
