### ISSUE TITLE
Converter for BigDecimal

### ISSUE THREAD

**Issue by xeonn** [canoo/dolphin-platform#326]
Hi,

Any plan to add datatype converter like BigDecimal?

Or .. is there any way for user to override converter factory and use it with something like setConverterFactory ?

Currently I am trying out the new v0.8.10.

**Comment by hendrikebbers** [comment]
Hi @xeonn ,
the Dolphin Platform provides a plugin system to add custom converters for new data types. An example can be found in the optional "dolphin-platform-date-time-converter" module that adds converters for the Java 8 date and time classes: https://github.com/canoo/dolphin-platform/tree/master/platform-extras/dolphin-platform-date-time-converter

You can find a first short description of the plugin API here: https://canoo.github.io/dolphin-platform/#_custom_data_types

We have an issue to add additional data types like BigDecimal in future by default: https://github.com/canoo/dolphin-platform/issues/98

Maybe you are interested in doing a Pull Request that adds BugDecimal support? By doing so we could provide it with the next release ;)

**Comment by xeonn** [comment]
Hi,
Thanks for the pointer and example. I'll see what I can do with it.

**Comment by xeonn** [comment]
Merge done by Hendrik.
