### ISSUE TITLE
exception text does not contain required information

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#330]
> ReflectionHelper: can not extract parameterized type!
> java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
> 	at com.canoo.dolphin.impl.ReflectionHelper.getTypeParameter(ReflectionHelper.java:177)
> 	at com.canoo.dolphin.impl.ClassRepositoryImpl.createClassInfoForClass(ClassRepositoryImpl.java:128)
> 	at com.canoo.dolphin.impl.ClassRepositoryImpl.access$000(ClassRepositoryImpl.java:44)
> 	at com.canoo.dolphin.impl.ClassRepositoryImpl$1.modelStoreChanged(ClassRepositoryImpl.java:66)
> 	at org.opendolphin.core.ModelStoreListenerWrapper.modelStoreChanged(ModelStoreListenerWrapper.java:57)
> 	at org.opendolphin.core.ModelStore.fireModelStoreChangedEvent(ModelStore.java:344)
> 	at org.opendolphin.core.ModelStore.add(ModelStore.java:137)

what I need is what field in which bean caused the problem

**Comment by kunsingh** [comment]
Fixed.
