### ISSUE TITLE
Add logging about the configuration on server

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#339]
is the property file used?
What properties are defined by the file

**Comment by hendrikebbers** [comment]
@kunsingh Have you done this? Otherwise it should be moved to version 0.9.

**Comment by kunsingh** [comment]
Yes I am done.

**Comment by timo0** [comment]
is this already merged or is for this issue a pull request issued?

**Comment by timo0** [comment]
https://github.com/canoo/dolphin-platform/pull/368

**Comment by timo0** [comment]
merged
