### ISSUE TITLE
Documentation how to run tests locally on Safari

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#341]
Currently the tests do not run on a mac since Safari is not working with the given test infrastructure.

**Comment by kunsingh** [comment]
Where to put the documentation.

To Run Web Component Test Locally on Safari -

1. stall the latest SafariDriver extension from here (SafariDriver.safariextz) -
2. http://selenium-release.storage.googleapis.com/2.48/SafariDriver.safariextz
3. Open Safari -> preferences -> Advanced, Check the box ‘Show Develop menu bar’
4. Click menu option ‘Develop’  and click ‘Allow Remote Automation’

**Comment by hendrikebbers** [comment]
added it to the build.adoc in the documentation
