### ISSUE TITLE
new project with multi client

### ISSUE THREAD

**Issue by mostfa-ayad** [canoo/dolphin-platform#348]
hi
thanks alot
the dolphin platform is amazing 

how can i start a project with 3 clients and one server android and web and javafx

**Comment by hendrikebbers** [comment]
The easiest way is to create such a project by using the maven archetype. A tutorial can be found here: https://canoo.github.io/dolphin-platform/#_creating_a_project_with_maven
This currently is missing an Android client that must be added by hand.

If you want to setup a project by hand this documentation will be helpful: https://canoo.github.io/dolphin-platform/#_creating_a_project_by_hand
