### ISSUE TITLE
Lazy loading of data in JavaFx

### ISSUE THREAD

**Issue by drenda** [canoo/dolphin-platform#353]
Hi,
this is a feature request. Would be like that Dolphin could loading lazy data from the database (using JPA, Hibernate).
Would be also nice have a way to load data in a TableView permitting pagination (triggered by scrolling, so something like infinite scroll components) with lazy loading of data.
If I've thousands of rows it's absurd load everything and the pagination is something very needed.

Thanks

**Comment by drenda** [comment]
Hi, some considerations about this topic? Thanks

**Comment by timo0** [comment]
Hi,

this feature is possible to do with the Dolphin Platform. For internal usage of canoo we have done this as an example. 

Currently there are no decisions done to open source the examples or not - we're sorry that we can't share the code with you yet.

**Comment by drenda** [comment]
I understand. Please update this ticket if there are some news about that. Thanks

**Comment by timo0** [comment]
will do! thanks for waiting :)

**Comment by hendrikebbers** [comment]
Sample for lazy loading added https://github.com/canoo/dolphin-platform/pull/753
