### ISSUE TITLE
DolphinListener is not setup in Spring

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#354]
We define a custom DolphinListener in our Spring Boot project. Unfortunately it is not setup correctly and the first time it is used, an Exception is thrown. I added @Component and @Scope("session") to make it work.

**Comment by hendrikebbers** [comment]
Can you share the code?

**Comment by netopyr** [comment]
You have access to the code, don't you? ;)

**Comment by kunsingh** [comment]
Error StackTrace -

`com.canoo.dolphin.server.context.DolphinContextException: Error while handling onSessionCreated listener

.... 
....
aused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.canoo.dolphin.todo.server.MyCustomListener] is defined at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE] at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1066) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE] at com.canoo.dolphin.server.spring.AbstractSpringContainerManager.createListener(AbstractSpringContainerManager.java:52) ~[main/:na] at com.canoo.dolphin.server.bootstrap.DolphinPlatformBootstrap$3.call(DolphinPlatformBootstrap.java:165) ~[main/:na] at com.canoo.dolphin.server.bootstrap.DolphinPlatformBootstrap$3.call(DolphinPlatformBootstrap.java:162) ~[main/:na] at com.canoo.dolphin.server.context.DolphinSessionLifecycleHandler.onSessionCreated(DolphinSessionLifecycleHandler.java:54) ~[main/:na]`
