### ISSUE TITLE
Add Controller tests to Maven Archetype

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#369]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
The maven archetype (see https://github.com/canoo/dolphin-platform-spring-boot-archetype) should contain at least one controller test that shows a developer how to write tests. Examples for controller tests can be found in the integration-tests modules or the todo-sample.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by joergsesterhenn** [comment]
I'd like to do this. I have made one pull request before but never really contributed, since the PR was not accepted - does this count?

**Comment by hendrikebbers** [comment]
That's fine :)

You can find samples of controller tests [here]/https://github.com/canoo/dolphin-platform/tree/master/platform-integration-tests/integration-server/src/test/java/com/canoo/dolphin/integration/server) and [here](https://github.com/canoo/dolphin-platform/tree/master/platform-examples/todo-example/todo-server-spring/src/test/java/com/canoo/dolphin/todo/server).

The documentation for the test API is [here](https://canoo.github.io/dolphin-platform/#_spring_controller_tests)

The Maven Artifact is not part of our main repository.  You can find it [here](https://github.com/canoo/dolphin-platform-spring-boot-archetype). Hope you are familiar with how maven archetypes are defined. The structure is different to a regular java project.

**Comment by joergsesterhenn** [comment]
Thanks I am familiar with maven archetypes.

**Comment by joergsesterhenn** [comment]
Would you assign me to this issue?

**Comment by hendrikebbers** [comment]
I need to check how I can do that. Already tried it but it looks like I can not assigne a issue to people that are not part of the Canoo team. :(

**Comment by timo0** [comment]
Thanks for helping us! The assignment is only possible of team members but you can go without beeing assigned :)

**Comment by joergsesterhenn** [comment]
Ok 😃

**Comment by joergsesterhenn** [comment]
Is it possible that @hendrikebbers already added an example of a [controller test](https://github.com/canoo/dolphin-platform-spring-boot-archetype/blob/master/src/main/resources/archetype-resources/server/src/test/java/controller/MyControllerTest.java) to the archetype ❓ 

I am not sure if this is what you were looking for, but I guess that is what I would have implemented - if it wasn't already there 😕

**Comment by hendrikebbers** [comment]
Oh s**t,
I have not seen that when creating the issue :(
I‘m really sorry about that

**Comment by hendrikebbers** [comment]
You are right. That is exactly what the issue describes

**Comment by hendrikebbers** [comment]
Looks like someone (me) missed to close the issue. Will do it now. Really sorry about that

**Comment by joergsesterhenn** [comment]
No probs, just thought I was maybe missing something 😄

**Comment by joergsesterhenn** [comment]
Please suggest anything else I should do now that I know my way around a little. I'd really like to contribute something other than closing this issue...

**Comment by hendrikebbers** [comment]
Sure, you take any issue with the 'good first issue' label that are made for a first issue and often are quite easy. See https://github.com/canoo/dolphin-platform/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Good one are https://github.com/canoo/dolphin-platform/issues/631 or https://github.com/canoo/dolphin-platform/issues/655
