### ISSUE TITLE
Update the release workflow to support bugfix releases

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#372]
- we need to create release branches for all repos
- we need to update the release documentation
- we need to create a bugfix-release documentation

**Comment by timo0** [comment]
As Kunal and I did the latest release we noticed following the documentation the master of the java repos is not up to date with the version numbers. Should we add an additional step to change the version numbers to (n+1)-SNAPSHOT or something like that?

**Comment by timo0** [comment]
In the documentation for updating the maven archetype the new angular client is missing

**Comment by hendrikebbers** [comment]
#379
