### ISSUE TITLE
Provide IntelliJ Plugin to create getter & setter

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#375]
We should provide an IntelliJ Plugin that generates DP getter and setter the right way

**Comment by hendrikebbers** [comment]
Example code for JavaFX Properties: https://github.com/JetBrains/intellij-community/tree/master/plugins/javaFX/src/org/jetbrains/plugins/javaFX/codeInsight

**Comment by timo0** [comment]
Is submitted to Intellij Repo

**Comment by hendrikebbers** [comment]
🤘

**Comment by timo0** [comment]
see https://plugins.jetbrains.com/plugin/9581-dolphinplattform-intellij-plugin/update/33633
and https://canoo.github.io/dolphin-platform/#_dolphin_platform_intellij_plugin
