### ISSUE TITLE
dolphin-platform-angular.js: missing implementation for onBeanRemovedHandler

### ISSUE THREAD

**Issue by andreashenle** [canoo/dolphin-platform#380]
The correct implmentation for to remove beans is missing:
Current version:  

`
onBeanRemovedHandler: function(bean) {
            $log.debug('Bean ' + JSON.stringify(bean) + ' removed');
            $rootScope.applyInAngular();
        },
`

**Comment by kunsingh** [comment]
This is not an issue with dolphin-platform-angular. I have changes couple of things to KAPO project and seems its working fine at my ends. 
- Use the latest or at least 0.8.13 version of 'dolphin-platform-angularjs' in bower.json
 **"dolphin-platform-angularjs": "0.8.13"**
- In build.config.js keep only 'dolphin-platform-angular.js'. It includes 'dolphin-platform.js'
**// 'vendor/dolphin-platform-js/dist/dolphin-platform.js',
 vendor/dolphin-platform-angularjs/dist/dolphin-platform-angular.js',**

**Comment by hendrikebbers** [comment]
We will discuss this at the daily :)
