### ISSUE TITLE
Challenged with Starting An OpenDolphin 0.9.0 Project that Uses SpringBoot at the Serverside and JavaFX for the client combined.

### ISSUE THREAD

**Issue by jermsam** [canoo/dolphin-platform#428]
My challenge is with jumpstarting a dolphin project. Each of the options I try does so with various errors that I find hard to debug. For that reason, I decided to follow a link that Mr. Hendrick Ebbers [the one who advised me to try dolphins for my needs] gave me.(https://github.com/canoo/dolphin-platform). When i follow that, I am left with only 12 errors as you can see in the attached photo. I tried manuaally including all the dependencies that are reported missing but still it did not solve all errors. [The error of "missing artifact com.canoo.dolphin-platform:dolphin-platform-client-javafx:0.9.0" persisted. It's now coming to 3 days when I am trying to get a solution to this challenge so that i can learn this awesome platform but I am not getting anywhere. Tried the "archetype" approach from https://www.youtube.com/watch?v=e0vdf0coNuc and http://www.guigarage.com/2015/12/dolphin-platform-jumpstart/. Watched the different JavaOne Talks At JavaOne posted on You tube, followed the documentations (http://open-dolphin.org/download/guide/guide/howto.html and tried searching in various blogs and forums available online) but in vain.
I will be more than grateful for your help. Thanks.
Best Regards,
Samson Ssali,
JITPOMI.INC
![dolphinerror](https://cloud.githubusercontent.com/assets/11094475/24346180/fc504410-12db-11e7-9979-fe52dec929cf.PNG)

**Comment by jermsam** [comment]
Even when I try using Gradel, I get the error in the attached photo
![dolphinerror2](https://cloud.githubusercontent.com/assets/11094475/24346267/33e8bbd2-12dc-11e7-969c-95f4aaebfc83.PNG)

**Comment by jermsam** [comment]
It's not my first maven project. Even while using Spring and DataFX I was using Maven. I also do not think it's a proxy issue, for other dependecies that I add are included successfully without any error. plus I have turned off my proxy but the problem remains.
Thank you

**Comment by hendrikebbers** [comment]
@jermsam mmmh, looks like you did everything right... This is a freaky problem. 
As you can see [here](https://search.maven.org/#artifactdetails%7Ccom.canoo.dolphin-platform%7Cdolphin-platform-client%7C0.9.0%7Cjar) the JAR that is missing is already uploaded to Maven Central.
I had a similar problem some time ago with a different library. It looked to my like there was an error by downloading a JAR from Maven central (connection problem or something). Based on this the JAR was not downloaded completely. Based on this a broken JAR file was on my machine in the local maven repository. I removed the Jar by hand and restarted the Maven build. This solved my problem. You can try the same by removing the `dolphin-platform-client` jar by hand. In you user folder you will find a hidden `.m2` directory. This directory contains the local maven repository. Please try to remove the dolphin platform jar here and restart the maven build.

**Comment by jermsam** [comment]
Thanks Hendrik: Should I remove all that is shown in this picture or only the dolphin platform folder?
![dolphin-platform repository](https://cloud.githubusercontent.com/assets/11094475/24348147/50a79f48-12e3-11e7-8e2d-9da6d75a7ac9.PNG)

**Comment by hendrikebbers** [comment]
Both should work

**Comment by jermsam** [comment]
Thanks Hendrik Ebbers. I had to do it over and over again until when it finally worked.I now have no error as you can see:
![problemsolved](https://cloud.githubusercontent.com/assets/11094475/24357791/76f2802c-1307-11e7-9713-0dd36dad6fa9.PNG)

**Comment by jermsam** [comment]
Only problem is when I try the calculator trial example, I get an error on the line:
@DolphinController(Constants.CONTROLLER_NAME)
Saying the constant CONTROLLER_NAME can not be resolved.

**Comment by timo0** [comment]
This looks like wrong dependencies between module. Usually the Constants Class/Interface is located in the common module and the Controller in the Server module. Have you defined a dependency between Server and Common?

**Comment by jermsam** [comment]
No Timo. I have not done so because I am do not know how to do so. i am just new at Dolphin and Open Dolphin. I however defined a common package in me project. can you help me on how to do this? i am following Henrick Embbers' tutorial @ http://www.guigarage.com/2015/10/dolphin-platform-how-to-create-an-application/ Thanks.

**Comment by timo0** [comment]
Ah sorry, looks like hendrik missed to mention the Constants Interface. You can simply add following interface to your Project:
`
public interface Constants {
    String CONTROLLER_NAME = "CalculatorController";
}
`

**Comment by jermsam** [comment]
Thanks Boss. Meaning Each time I meet Constants.SOME_CONSTANT I just know it has to be included in this Constant for reasons as explained in the Open Dolphin documentation as highlighted in the photo..... Ok. thanks Timo0
![constants interface](https://cloud.githubusercontent.com/assets/11094475/24366867/2a9873aa-1323-11e7-876f-47fd4e98c571.PNG)

**Comment by timo0** [comment]
you're welcome :-)

**Comment by jermsam** [comment]
At this stage, when directly creating the connection to our Dolphin Platform based server application that is defined by the ClientContext class, I get an error on this line:
ClientConfiguration config = new JavaFXConfiguration("http://localhost:8080/dolphin");
reading 
 "the Constructor JavaFXConfiguration(String) is undefined"
Do I have to define this manually somewhere also?

**Comment by timo0** [comment]
The constructor of com.canoo.dolphin.client.javafx.JavaFXConfiguration takes only an String as argument. Which Version of DolphinPlatform are you using?

**Comment by jermsam** [comment]
I am using version 0.9.0

**Comment by timo0** [comment]
Can you try `new URL("http://localhost:8080/dolphin")`

**Comment by jermsam** [comment]
Using new URL("http://localhost:8080/dolphin") from import java.net.URL undoes the compilation bug. Thanks Timo0.

**Comment by jermsam** [comment]
I can now successfully sync the JavaFX Client with the RESTful Spring Server using Dolphin. Could you please assist me on how to go about persisting. I want to store this data in a Derby (for the start) database using Hibernate as my ORM. Noticing that in Hendrik's Tutorial, the definition for SpringDataRepository and CalcEntity is missing, I suppose that I should add this myself. So I went to my pom.xml and included:

  <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.6.RELEASE</version>
		<relativePath/> 
	</parent>
then added these dependencies
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derby</artifactId>
			<scope>runtime</scope>
		</dependency>

**Comment by timo0** [comment]
for a CRUD Example please see https://github.com/canoo/dolphin-platform/issues/404

**Comment by jermsam** [comment]
I then created:
public class SpringDataCalcRepository extends CrudRepository<CalcEntity, Long>{

}
AND the CalcEntity the Hybernate way. 

However:
1. CrudRepository is not recognised and
2. @Inject annotation does not work.

Did I follow the wrong path? What must I have done?

**Comment by timo0** [comment]
Please use the example from #404 as guide. This issue is not regarded to DolphinPlatfrom please consult other sources to resolve them.

**Comment by jermsam** [comment]
Ok. Thanks very much. I am grateful for the help. I am going to follow both the issue and example. I already downloaded it.
