### ISSUE TITLE
Challenged In Making A Master-Detail Application

### ISSUE THREAD

**Issue by jermsam** [canoo/dolphin-platform#431]
Hello.

I am doing a master-detail kind of application. To test how I am going to go about it, I have started with 3 simple views.
1. Table.fxml : showing a list of topics and their description. [This I have successfully done.] as you can see:
![tablefxml](https://cloud.githubusercontent.com/assets/11094475/24613791/01a6ccd4-1892-11e7-8fc7-564d89599fbd.PNG)
2. Form.fxm: does the CRUD operations on the Topics data. [This also I have successfully done as a stand alone] as you can see:
![formfxml](https://cloud.githubusercontent.com/assets/11094475/24614053/c1d0e152-1892-11e7-81d6-559e7f2278d1.PNG)
3. Main.fxml: Is supposed to house both Table.fxml and Form.fxml. As shown in the figure below:
![masterfxml](https://cloud.githubusercontent.com/assets/11094475/24614881/504fc216-1895-11e7-9b9f-16e7e23c968f.PNG)

I have defined TopicViewBean.java like this:

`
@DolphinBean
public class TopicViewBean {
	private Property<TopicBean> bean;

	 public Property<TopicBean> beanProperty() {
	        return bean;
	    }

	    public TopicBean getBean() {
	        return bean.get();
	    }

	    public void setBean(TopicBean bean) {
	        this.bean.set(bean);
	    }
	
	private Property<TopicListBean> listBean;
	
	 public Property<TopicListBean> listBeanProperty() {
	        return listBean;
	    }

	    public TopicListBean getListBean() {
	        return listBean.get();
	    }

	    public void setListBean(TopicListBean listBean) {
	        this.listBean.set(listBean);
	    }
}

`
My challenge is with defining TopicBinder.java and TopicController.java to ensure that the Table           part and the Form part of my MainView work as they did when they where still standing alone. 
Here is my TopicView.fxml:
`
<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="650.0" xmlns="http://javafx.com/javafx/8.0.40" xmlns:fx="http://javafx.com/fxml/1">
   <children>
      <VBox alignment="CENTER" prefHeight="400.0" prefWidth="600.0" spacing="10.0" AnchorPane.bottomAnchor="10.0" AnchorPane.leftAnchor="10.0" AnchorPane.rightAnchor="10.0" AnchorPane.topAnchor="10.0">
         <children>
            <HBox alignment="CENTER" prefHeight="100.0" prefWidth="200.0" VBox.vgrow="ALWAYS" />
            <HBox alignment="CENTER" layoutX="10.0" layoutY="10.0" prefHeight="100.0" prefWidth="200.0" VBox.vgrow="ALWAYS">
               <children>
                  <fx:include fx:id="table" source="TableView.fxml" />
               </children>
            </HBox>
            <HBox alignment="CENTER" layoutX="10.0" layoutY="110.0" prefHeight="83.0" prefWidth="630.0" VBox.vgrow="ALWAYS">
               <children>
                  <fx:include fx:id="form" source="FormView.fxml" />
               </children>
            </HBox>
         </children>
      </VBox>
   </children>
</AnchorPane>
         </children>
      </VBox>
   </children>
</AnchorPane>
`
Thank you.

**Comment by jermsam** [comment]
I read somewhere that i could use  the Dolphin Platform event bus but I am not so sure how to do this. Could someone help out please? Thank you.

**Comment by timo0** [comment]
please see #404 for an Master-Detail Example. This is not implemented using the event bus because for Master-Detail-Views the Eventbus is not required.

**Comment by jermsam** [comment]
Thanks Timo0. Let me look at that.

**Comment by jermsam** [comment]
Hello timo0.
I used the example provided at #404 to be able to fetch data from the DB and update a javaFX TableView (in a separate scene, call it Table.fxml) and also to update database data from JavaFX of the form controls (in another scene call it Form.fxml). My challenge is not in the CRUD aspect of the app but rather in ensuring that I combine both the Table.fxml and Form.fxml into View.fxml and attain the same functionality I did with using Table.fxml and Form.fxml independently. I realize that #404 deals with the CRUD aspect only.

**Comment by timo0** [comment]
Hi @jermsam,
this is not an DP related topic. Please use other sources (like http://stackoverflow.com/questions/29256848/javafx-include-fxml-in-fxml-without-controller).

**Comment by jermsam** [comment]
Ok. timo0. Thanks for the hint. Let me try that source.

**Comment by hendrikebbers** [comment]
Hi @jermsam ,
as far as I understand you both views (master & detail) are running fine with Dolphin Platform. Now you want to combine them and create an application where you can open the detail view from the master view, right?

**Comment by jermsam** [comment]
Yes @hendrkebbers

**Comment by jermsam** [comment]
You see, I am learning how I can combine Dolphin functionality with DataFX functionality.

**Comment by jermsam** [comment]
My target is to be able to create a TableView that is updated through JavaFX formcontrols but when you click twice on the TableView rows, you are redirected to a Scene that shows the details of the data in the clicked row.

i.e:If I was using Spring exclusively;
For Example
My REST http address would be: http://localhost:8080/topics/someTopic/lessons
now in my table.fxml, I have topics data like id,name,description
in my form.fxml, I can do CRUD operations on topics data. e.g when I click on table.fxml row, my form controls receive that data and I can edit it
NOW
when I double click on table.fxml row that describes a topic whose id is "someTopic", I should be redirected to a scene showing lessons specific to "someTopic".
I believe that once I achieve that, I would have mastered the Master-Detail case with Dolphin and DataFX. Thank you.

**Comment by jermsam** [comment]
@timo0 I looked at the link you refered me to and it sort of addresses something else other than what I wanted. i can do a master-detail application without dolphin but with the plain javafx but I am finding a problem having my two views above to communicate with each other when combined in a single view. @hendrikebbers  understood my concern i think.

**Comment by jermsam** [comment]
@hendrikebbers , i tried achieving the solution by using a combination of DataFX's flow API and Dolphin platform. The challenge I am finding however is that, the two reference the scene differently:
With  DataFX, the main method would be something like:
`
public class Main extends Application {
	@Override
	public void start(Stage primaryStage) throws FlowException {
		Flow flow  = new Flow(MainController.class);
		FlowHandler flowHandler = flow.createHandler();
		StackPane pane = flowHandler.start(new DefaultFlowContainer());
        primaryStage.setScene(new Scene(pane));
        primaryStage.show();
		
	}
	
	public static void main(String[] args) {
		launch(args);
	}

	
	
}
`
while with dolphin it has to be:

`
public class Main extends DolphinPlatformApplication {

    @Override
    protected URL getServerEndpoint() throws MalformedURLException {
        return new URL("http://localhost:8080/dolphin");
    }

    @Override
    protected void start(Stage primaryStage, ClientContext clientContext) throws Exception {
        MainViewBinder view = new MainViewBinder(clientContext);
        Scene scene = new Scene(view.getParent());
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String... args) {
        launch(args);
    }
}
`
Now I can't figure out how to combine these two notions. When I do, I believe I will be good to go. Can someone help me out please?

**Comment by Andrew010492** [comment]
Hey @Jermsam, you can try this:

<  public class ClientApplication extends Application {
private static ClientContext clientContext;

@Override
public void init() throws Exception {
  ClientConfiguration config=
		  new JavaFXConfiguration(new URL("http://localhost:8080/dolphin"));
  clientContext=ClientContextFactory.connect(config).get();
}

    @Override
	public void start(Stage primaryStage) throws Exception {
    	
    	URL url =ClientApplication.class.getResource("view/view.fxml");
		FXMLLoader loader= new FXMLLoader(url);
		MyView viewController=new MyView(clientContext);
		loader.setController(viewController);
		StackPane stackPaneMaster=loader.load();
		Scene scene = new Scene(stackPaneMaster);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String... args) {
        launch(args);
    }
    public static ClientContext getClientContext() {
		return clientContext;
	}
} >

**Comment by Andrew010492** [comment]
"but you need to ensure that your binder class extend AbstractViewBinder<M> instead of AbstractFXMLViewBinder<M>"

**Comment by Andrew010492** [comment]
"when you do this, you can use the conventional navigation techniques for JavaFx navigation. Now about using it with dataFX ask @HendrickEbbers"
