### ISSUE TITLE
Create a sample to demonstrate web deployment of a DolphinPlatform application

### ISSUE THREAD

**Issue by janakmulani** [canoo/dolphin-platform#454]
At present we have some sample apps like to-do list as part of DolphinPlatform code. These can be be run using SpringBoot.

We need to demonstrate how a DolphinPlatform application can be deployed as a war in an app server. 

We have created a simple DolphinPlatform App app (the one created by the DolphinPlatform Maven Archetype) and modified it such that:
1. A war can be generated for deployment in an app server
2. App's Polymer-client is part of the war and can be started directly by typing the url of client's html file in a browser
3. App's Fx-client is part of the war and can be started directly by typing the url of client's jnlp file in the browser.

**Comment by timo0** [comment]
The client application crash right after start. By trying to debug the application we noticed that we can't debug things done in background threads. So my thoughts going to issues with the BackgroundExecutor  in Webstart Environments. 

This should be investigated in more detail.

**Comment by hendrikebbers** [comment]
Update to 0.12.0 do not fix this

**Comment by hendrikebbers** [comment]
Looks like this is based on cookie parsing

**Comment by janakmulani** [comment]
I made some progress.
I changed HttpClientCookieHandler.updateCookiesFromResponse :
        Map<String, List<String>> headerFields = conn.getHeaderFields();
        List<String> cookiesHeader = headerFields.get(PlatformConstants.SET_COOKIE_HEADER);
        if (cookiesHeader != null) {
            LOG.debug("found '{}' header field", PlatformConstants.SET_COOKIE_HEADER);
            for (String cookie : cookiesHeader) {
>>                if (cookie == null) {
>>                    continue;
>>               }

After making this change if I type http://localhost:8080/WebDeployment/fxclient/fxclient.jnlp in the browser then:
1. JWS starts
2. It does not crash anymore
3. I get DP connection time out error
4. DP  asks me to reconnect.
5. On reconnect the app starts OK.

**Comment by hendrikebbers** [comment]
@janakmulani cool! Can you do a PR?

**Comment by janakmulani** [comment]
Web Deployment with gradle : web-deployment branch has been pushed. Changed the DP Fx Client class to extend SimpleDolphinPlatformApplication. Also there is a fix in HttpClientCookieHandler.
