### ISSUE TITLE
ClassCastException on the server when looking up beans by id

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#48]

**Comment by hendrikebbers** [comment]
@aalmiray / @netopyr Any idea what this issue describes?

**Comment by aalmiray** [comment]
The server is unable to find beans whose id property has been defined as a `Long`. Apparently a value of type `Integer` is injected instead, causing a CCE.

Exception on server side:

    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

The following bean runs into trouble

    import com.canoo.dolphin.mapping.DolphinBean;
    import com.canoo.dolphin.mapping.Property;

    @DolphinBean
    public class SampleBean {
        private Property<Long> id;

        public Property<Long> idProperty() {
            return id;
        }

        public void setId(Long id) {
            this.id.set(id);
        }
    }

This looks like a JSON codec issue.

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform/issues/97
