### ISSUE TITLE
Check if we can use new GSON version

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#515]
Check if we can use new GSON version. Maybe by doing so the code in the command encoders can be simplified.

**Comment by aalmiray** [comment]
Consider overhauling all dependencies, not just GSON, such as

	groovyVersion     = 2.4.11
	gsonVersion       = 2.8.1
	guavaVersion      = 22.0
	jacocoVersion     = 0.7.9
	rxjavaVersion     = 1.3.0
	slf4jVersion      = 1.7.25
	springBootVersion = 1.5.4.RELEASE

Running the `dependencyUpdates`gradle task at the root level ( `gradle :depUp`) yields

    The following dependencies have later milestone versions:
     - javax.enterprise:cdi-api [1.1 -> 2.0]
     - cglib:cglib-nodep [3.2.4 -> 3.2.5]
     - org.kt3k.gradle.plugin:coveralls-gradle-plugin [2.6.3 -> 2.8.1]
     - org.apache.deltaspike.core:deltaspike-core-api [1.7.1 -> 1.8.0]
     - org.apache.deltaspike.core:deltaspike-core-impl [1.7.1 -> 1.8.0]
     - com.avast.gradle:docker-compose-gradle-plugin [0.3.13 -> 0.4.3]
     - com.jfrog.bintray.gradle:gradle-bintray-plugin [1.7.1 -> 1.7.3]
     - org.ajoberstar:gradle-git [1.3.2 -> 1.7.2]
     - com.github.ben-manes:gradle-versions-plugin [0.13.0 -> 0.15.0]
     - com.google.code.gson:gson [2.7 -> 2.8.1]
     - com.google.guava:guava [19.0 -> 22.0]
     - com.hazelcast:hazelcast-client [3.6.2 -> 3.8.2]
     - org.hibernate:hibernate-validator [5.1.3.Final -> 5.4.1.Final]
     - javax:javaee-api [6.0 -> 7.0]
     - org.glassfish:javax.el [3.0.0 -> 3.0.1-b08]
     - javax.servlet:javax.servlet-api [3.1.0 -> 4.0.0-b07]
     - org.jmockit:jmockit [1.25 -> 1.32]
     - com.github.dblock:oshi-core [3.2 -> 3.4.0]
     - org.reflections:reflections [0.9.10 -> 0.9.11]
     - io.reactivex:rxjava [1.1.7 -> 1.3.0]
     - org.sonarsource.scanner.gradle:sonarqube-gradle-plugin [2.2 -> 2.5]
     - org.spockframework:spock-core [1.0-groovy-2.4 -> 1.1-groovy-2.4]
     - org.springframework.boot:spring-boot-starter-test [1.5.3.RELEASE -> 1.5.4.RELEASE]
     - org.springframework.boot:spring-boot-starter-web [1.5.3.RELEASE -> 1.5.4.RELEASE]
     - net.nemerosa:versioning [2.4.0 -> 2.6.0]

**Comment by hendrikebbers** [comment]
Thx for the Gradle  hint. I think we already have a general issue for that. Will link it

**Comment by TimRiemer** [comment]
Working on.

Would try to update all dependencies. 
@hendrikebbers is there a generell issue for that?

**Comment by hendrikebbers** [comment]
@TimRiemer yes we have https://github.com/canoo/dolphin-platform/pull/644

**Comment by hendrikebbers** [comment]
ah, you already found it :D
