### ISSUE TITLE
Wildfly 11 integration, Java 8, Java EE 7

### ISSUE THREAD

**Issue by ghostidentity** [canoo/dolphin-platform#518]
Hey guys,

Need help pls! I cant find good documentation on how to integrate open-dolphin to an application server ideally wildfly 11. I tried the maven archeotype that is provided in the website but its an standalone server.

Do opendolphin classloader compatible in ejb module ? If yes, how can i pass data between opendolphin and javafx application.

Looking forward for an answer.

Mark

**Comment by hendrikebbers** [comment]
Hi,

adding it to Wildly is quite easy.

add the following dependency to your server project:

```
<dependency>
    <groupId>com.canoo.dolphin-platform</groupId>
    <artifactId>dolphin-platform-server-javaee</artifactId>
    <version>0.14.0</version>
</dependency>
```

Once this is done DP will boot automatically.

Now you can simply define controller classes in your server project. See https://canoo.github.io/dolphin-platform/#_controller_api for some help

The controller class instances will be managed by Wildly and you can simply use CDI in them.

**Comment by hendrikebbers** [comment]
@ghostidentity does this answer your question?

**Comment by ghostidentity** [comment]
Thank you! but im still having trouble to test the controller api. I followed the instruction from the site; but the code provided is incomplete. 

Screenshot:
![screenshot](https://user-images.githubusercontent.com/4637625/27226126-10ff8a36-52d0-11e7-878d-45c7f0c80938.png)

Sourcecode: 
[codefromsite.zip](https://github.com/canoo/dolphin-platform/files/1080704/codefromsite.zip)

**Comment by hendrikebbers** [comment]
if you want I can have a look by sharing screen at Skype? What do you think?

**Comment by ghostidentity** [comment]
Sure, that would be a big help if you can check all configurations I've made.  May i know your skype id.

**Comment by hendrikebbers** [comment]
you should have a mail

**Comment by ghostidentity** [comment]
sure mine is proxyshadow@gmail.com
