### ISSUE TITLE
Provide client API for Polymer 2

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#532]
Currently we only support Polymer 1.x

**Comment by hastebrot** [comment]
Per Polymer 2.x documentation (https://www.polymer-project.org/2.0/docs/upgrade#before-you-begin) we should target the following component versions (ranges):

- **Polymer:** ^2.0.0
- **webcomponentsjs:** ^1.0.0
- **web-component-tester:** ^6.0.0
- **Polymer elements:** ^2.0.0

**Comment by hastebrot** [comment]
At least some of the official Polymer elements provide support for both Polymer 1.9 and 2.x.

~~~json
  "dependencies": {
    "polymer": "Polymer/polymer#1.9 - 2",
~~~

via: https://github.com/PolymerElements/paper-input/blob/56089b9e2e6609fc1d0e3a34be9a9e332f2a1b4b/bower.json#L30-L31

Seems they instruct Travis CI to install multiple variants (i.e. Polymer 2.x with Web Components 1.x; Polymer 1.x with Web Components 0.x).

~~~yaml
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
~~~

via: https://github.com/PolymerElements/paper-input/blob/56089b9e2e6609fc1d0e3a34be9a9e332f2a1b4b/.travis.yml#L3-L5

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform-polymer/pull/14
