### ISSUE TITLE
CME in BeanRepository

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#54]
There's a pair of CMEs in `BeanRepository` when iterating over the list of listeners

``` java
void registerBean(Object bean, PresentationModel model, UpdateSource source) {
        objectPmToDolphinPm.put(bean, model);
        dolphinIdToObjectPm.put(model.getId(), bean);

        if (source == UpdateSource.OTHER) {
            for (final BeanAddedListener beanAddedListener : beanAddedListenerMap.get(bean.getClass())) {
                beanAddedListener.beanCreated(bean);
            }
            for (final BeanAddedListener beanAddedListener : anyBeanAddedListeners) {
                beanAddedListener.beanCreated(bean);
            }
        }
    }
```

It's possible for a listener to grab hold of it's subscription and cancel it as its last step. If so, it will modify the currently iterated list and trigger a ConcurrentModificationException.

**Comment by hendrikebbers** [comment]
@kunsingh we should check if this error still happens

**Comment by hendrikebbers** [comment]
Something like `Subscription s = myProperty.onChange(e -> s.unsubscribe());`

**Comment by hendrikebbers** [comment]
@kunsingh have you already tried this?

**Comment by kunsingh** [comment]
I tried...there is no CME.
