### ISSUE TITLE
Error when calling an DolphinAction with null param value

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#542]
Hi team, with v0.15.0 a call like this, kills the session:

invoke("action2",new Param("firstArg",null));

The problem is located in class ValueEncoder; setting a breakpoint in the last line of encodeValue() helps. I am not exactly sure, but think there is an explicit handling for value == null missing.

 static JsonElement encodeValue(Object value) {
        if (value instanceof String) {
            return new JsonPrimitive((String) value);
        }
        if (value instanceof Number) {
            return new JsonPrimitive((Number) value);
        }
        if (value instanceof Boolean) {
            return new JsonPrimitive((Boolean) value);
        }
        throw new IllegalStateException("Only String, Number, and Boolean are allowed currently");
    }

**Comment by hendrikebbers** [comment]
#543
