### ISSUE TITLE
Support for small Objects with custom converters

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#55]
Often one wants to use small Objects (e.g. Date, Enum) that can be easily mapped to a single primitive value. Would be nice to be able to specify a converter so that the Platform does the conversion automatically.
(As a first Step the JavaFX FXBinder class supports converters)

**Comment by hendrikebbers** [comment]
In JavaFX the FXBinder will support converters for properties and lists beginning with Version 0.8. This can be used as a workaround until we can register general converters

**Comment by hendrikebbers** [comment]
see #75

**Comment by hendrikebbers** [comment]
PR: #263
