### ISSUE TITLE
Cleanup logs

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#56]
Currently we throw a bunch of Exceptions in the server log, which have to be ignored. This is extremely distracting during application development and bears the risk of overlooking an important Exception.

**Comment by hendrikebbers** [comment]
@aalmiray Can I close this issue?

**Comment by aalmiray** [comment]
Why? What has changed that makes you think this issue should be closed?

**Comment by hendrikebbers** [comment]
The exceptions on server start are removed. Are there any other exceptions in the server log?

**Comment by netopyr** [comment]
I created this issue originally and yes, it is fixed.
