### ISSUE TITLE
Github Release for 0.16.1 is missing

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#566]
Looks like we have a 0.16.1 Release but this is missing in the github release overview

**Comment by timo0** [comment]
Sorry this was an accident for the JS releases. I've tried to automate the release process but this wasn't supposed to be pushed.

**Comment by timo0** [comment]
Luckily the only repos I've pushed to was the JS repos. I've removed the tag and I hope no one has already updated.
