### ISSUE TITLE
Add first version of JS based http client

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#609]
See https://github.com/canoo/dolphin-platform/issues/592 and the Java imply here https://github.com/canoo/dolphin-platform/pull/590

It is important that we can add handlers to the client that are used in every request / response. This is needed since we need to add the dolphin-client-id to each request and check it for each response. Once security is added a second handler is needed that does the same with JWT tokens.

**Comment by giftkugel** [comment]
The JavaScript client has now an implementation of a HTTP client.
The HTTP client API is nearly the same as the Java version.

For example:
`platformClient.getService('HttpClient').get('./index.html').withoutContent().readObject().execute().then(function(t) { console.log(t); });`
