### ISSUE TITLE
Add unit tests to JS projects

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#614]
Here we need a lot more tests.

**Comment by hastebrot** [comment]
JS projects that is:

- [dolphin-platform-js](https://github.com/canoo/dolphin-platform-js)
- [dolphin-platform-angularjs](https://github.com/canoo/dolphin-platform-angularjs)
- [dolphin-platform-polymer](https://github.com/canoo/dolphin-platform-polymer)

**Comment by giftkugel** [comment]
We currently have `342 passing (410ms)` tests for the `dolphin-platform-js 1.0.0-CR.4` with a coverage of `>=90%`
Current command for Mocha tests is: `npm test`
Current command for Mocha tests with code coverage is: `test:coverage`
We also do mutation testing for the `dolphin-platform-js` repository. The command is: `test:mutation`

**Comment by giftkugel** [comment]
Closed, because the issue is splitted into #867, #871 and #872
