### ISSUE TITLE
Readme: Should link to the corresponding section for subprojects

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#618]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
For instance https://github.com/canoo/dolphin-platform-angularjs/blob/master/README.md should have a link to https://canoo.github.io/dolphin-platform/#_the_angularjs_client_integration somewhere.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by singloon** [comment]
@hendrikebbers @hastebrot can I claim this issue?

**Comment by singloon** [comment]
So this requires changing the readme for the 4 client repositories?

**Comment by hendrikebbers** [comment]
@singloon yes

**Comment by singloon** [comment]
@hendrikebbers is there documentation for all the sub projects? In the documentation I can see information for Java ee integration, Spring integration and angular js integration.

**Comment by hendrikebbers** [comment]
@singloon no. Polymer & JS is still missing.

**Comment by singloon** [comment]
Please review https://github.com/canoo/dolphin-platform-angularjs/pull/11 for the updated documentation for angularjs

**Comment by singloon** [comment]
Also can you please review https://github.com/canoo/dolphin-platform-android/pull/4 for the updated documentation for Android

**Comment by hendrikebbers** [comment]
THX :)
