### ISSUE TITLE
JavaScript: Add npm scripts for install and build to package.json

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#619]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
npm allows us to define custom script calls in `package.json`(https://docs.npmjs.com/misc/scripts).

Since we already have `bower` in our `devDependencies` we can add a script entry to run `bower install`. This decreases the steps needed for installation and also provides a single point for developers to run the installation.

```json
"scripts": {
  "install:bower": "./node_modules/.bin/bower install",
  "test:gulp": "./node_modules/.bin/gulp verify"
}
```

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by BadJukeBox** [comment]
Hi I'd like to take this one, but there are multiple package.json files so i'm somewhat confused what needs to be done here?

**Comment by hendrikebbers** [comment]
@hastebrot can you help here?

**Comment by hastebrot** [comment]
Should be the `package.json` in the project root directory:

- https://github.com/canoo/dolphin-platform-angularjs/blob/master/package.json
- https://github.com/canoo/dolphin-platform-polymer/blob/master/package.json
- https://github.com/canoo/dolphin-platform-js/blob/master/package.json

Since each directory also contains a `gulpfile.js` I assume it is possible to build each project using Gulp.

The release guide contains the command to run a Gulp build: https://canoo.github.io/dolphin-platform/#_releasing_the_javascript_repositories

>As a next step the project must be build by using gulp. To do so call `gulp clean verify build` in the root folder of the project

It would be nice if we can have a `npm` command for this task.

**Comment by BadJukeBox** [comment]
So you want each package.json to contain the changes? If so that makes things clearer, as originally it seemed as though there was only one package to change.

**Comment by giftkugel** [comment]
The JavaScript client now contains the following NPM scripts `npm run <command>`

`clean` = Delete all build and test folders
`clean:all `= Like `clean`, but also removes the _node_modules_ folder
`build` = Start the Webpack build
`build:install` = Like `build` but will do an `npm install` before the build
`test `= Start the Mocha unit tests
`test:mocha` = Same as test
`test:coverage` = Start the Mocha unit tests with code coverage report
`test:serve` = Start a Webpack Dev server for some API tests in the browser
`test:mutation` = Start mutation testing with Stryker
`coverage` = Generate coverage report (need to run tests before)
`coveralls` = Generate coverage report and run Coveralls
