### ISSUE TITLE
Polymer: Provide a <dolphin-controller> element

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#623]
There should be a way to connect to a controller without having to use a behavior/mixin.

Research advantages/disadvantages and possible obstacles.

**Comment by hastebrot** [comment]
The `<iron-list>` demo page provides an example for orientation (https://github.com/PolymerElements/iron-ajax/blob/536c76a4206e08a16b364930855e46f58ce3565d/demo/index.html#L55-L69).

**Comment by hastebrot** [comment]
Let us analyze current approach.

`demo/index.html`:
- Imports the Polymer adapter: `<script src="../dist/dolphin-platform-polymer.js"></script>`.
- Connects to Dolphin: `clientContext = dolphin.clientContext("http://localhost:8080/dolphin");`.
- Handles connection errors: `clientContext.onConnect().then(...).catch(...);`.

`demo/todo-view.html`:
- Defines new element: `<dom-module id="todo-view">`.
- Uses Dolphin controller behavior: `behaviors: [clientContext.createBehavior("ToDoController")]`.

**Comment by hendrikebbers** [comment]
When creating a view in Polymer 2 it should contain a `<dolphin-controller>` component:

```
<script src="./bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="./bower_components/polymer/polymer-element.html">

<dom-module id="foo-element">
  <template>
    <dolphin-controller name=“MovieController” model=“[[model]]“></dolphin-controller>
    <h2>Hello</h2>
  </template>

  <script>
    class FooElement extends Polymer.Element {
      static get is() { return "foo-element"; }
    }
    window.customElements.define(FooElement.is, FooElement);
  </script>
</dom-module>
```

**Comment by hendrikebbers** [comment]
Thinking about hierarchies:
The polymer component must support https://github.com/canoo/dolphin-platform/pull/514

**Comment by hendrikebbers** [comment]
Polymer 2 should be ready at 16th October
