### ISSUE TITLE
Move Binding interface to common module

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#626]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
This should not be part of the client API. Can be used in server, too. Based on this the `Binding` interface should be moved to the core module.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by Nipel-Crumple** [comment]
Hi! I'd like to work on this issue.

**Comment by Nipel-Crumple** [comment]
@hendrikebbers Oops, It seems that I've broken build? Or it is connected with something else?

**Comment by Nipel-Crumple** [comment]
That is the problem from build log:
```
Caused by: You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator
```
What can I do with this?

**Comment by hendrikebbers** [comment]
Hi @Nipel-Crumple 
to run the build you only need to call `gradlew clean build` from the command line or IDE. Are you familiar with gradle? SonarQube is only for quality checks and will be called by travis automatically.

Next to gradle docker is needed to run the build since Dolphin Platform contains some integration tests that are based on docker.

Please ask me if you have any additional questions.

**Comment by Nipel-Crumple** [comment]
@hendrikebbers 
Yes, I'm familiar with gradle, and you're right, Travis failed the build because of SonarQube and I cannot understand, why it happened? As I see `.travis.yaml` should install all dependencies before bulding app, but it seems that there is some issue with SonarQube

**Comment by hendrikebbers** [comment]
@Nipel-Crumple can you create an issue for that. We currently have Travis builds based on docker integration and based on this I haven't checked the Travis result since it is not working. But this one is new to me. So please create an issue :)

**Comment by hendrikebbers** [comment]
Maybe you can try `gradlew clean build` on your local machine. If this is running we are fine (for the moment)
