### ISSUE TITLE
Move DefaultBidirectionalConverter to impl

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#629]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
The `DefaultBidirectionalConverter` class is currently not needed in public API. It can be moved to private API.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by ArkantosC** [comment]
Hi, is the idea move the class to com.canoo.dp.impl.client.javafx ?

**Comment by hendrikebbers** [comment]
Yes

Von meinem iPhone gesendet

**Comment by ArkantosC** [comment]
Working on it

**Comment by ArkantosC** [comment]
Created pull request and it is waiting for a reviewer.

**Comment by hendrikebbers** [comment]
Cool! Will have a look tomorrow 

Von meinem iPhone gesendet

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform/pull/676
