### ISSUE TITLE
Refactor the Eventbus public / private API to have a standardized version for DP & other framework like ULC 

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#636]
Based on some discussions with @janakmulani we will refactor some of the event bus classes to get a result that is independent from Dolphin Platform

**Comment by janakmulani** [comment]
We discussed the differences between EventBus for DP and ULC.

All DP apps are managed and DP EventBus is a singleton in SpringContext and can be injected in different DP sessions. Thus it is available to all DP controllers within a DP session and across two DP sessions.

All ULC apps are not managed. ULC. So ULCEventBus cannot be injected. It was made part of ULC Session and can be used only within a ULCSession. If two ULCSessions want to communicate over EventBus then they have to use Distributed Event bus like Hazelcast. There was a suggestion by Hendrik that for two instances (ULCSessions) of same application (two clients are connected) to communicate we could make the ULC Event Bus static. However this approach will not work as methods of a component such as Static ULCEvent Bus not created within a ULCSession will not be able to access ULCComponents of a ULCSessions as they ULCSession is ThreadLocal. Need to take a different approach.
