### ISSUE TITLE
Add version numbers to Docker base containers

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#649]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
Currently all docker base containers that are used for integration tests do not provide version numbers. Based on this always `latest` will be used. This can end in bad tests since different version will be used on different systems.

All Docker files can be found under `platform-integration-tests/integration-tests/docker-base` folder and currently the first line of each file looks like this:

`FROM airhacks/payara-configured`

Here a working version number should be added.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
Currently the different modules of our samples (see `platform-examples` folder) are named different in the samples (`server`, `common`, `client`, ...). All modules should be renamed based on the modules in the `process-monitor-sample` sample.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by vpondala** [comment]
Let me work on this

**Comment by hendrikebbers** [comment]
@vpondala cool! If you have any question just join our slack community channel: https://join-dolphin-platform-slack.herokuapp.com

**Comment by vpondala** [comment]
I had a look at the images in Dockerhub. I can't see any tags other than latest for airhacks/* images:

https://hub.docker.com/r/airhacks/payara-configured/tags/
https://hub.docker.com/r/airhacks/wildfly/tags/
https://hub.docker.com/r/airhacks/tomee/tags/
https://hub.docker.com/r/airhacks/java/tags/

Not sure what we can do here.

**Comment by hendrikebbers** [comment]
I will ask Adam Bean who is the maintainer of the files if he can do a release

**Comment by hendrikebbers** [comment]
Done: https://twitter.com/hendrikEbbers/status/920242006139588608
Let's wait for an answer :)

**Comment by hendrikebbers** [comment]
@vpondala interesting in creating custom docker containers that provide the needed infrastructure? In that case we can easily tag them on our own.

**Comment by hendrikebbers** [comment]
Tags are now available and added :)
