### ISSUE TITLE
Add support for @Past bean validation annotation

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#658]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
Currently the `dolphin-platform-bean-validation` module do not provide support for all default bean validation annotations. One that is missing is the `@Past` annotation. For solving this issue the support for the `@Past` annotation must be added like it is done for several other bean validation annotations in the `dolphin-platform-bean-validation` module and at least one unit test must check that the annotation is supported.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by Ampretuzo** [comment]
Aaaand I'll try to implement this as well.

**Comment by hendrikebbers** [comment]
@Ampretuzo ok, do you have knowledge in java bean validation? Do you want to do all 3 issues in one PR?

**Comment by Ampretuzo** [comment]
I'm not exactly an expert, but I've seen the code and it does not seem to be too difficult. If I'm mistaken correct me :)
If I'll encounter some difficulties I'll keep you posted.
Yes, one PR.

**Comment by hendrikebbers** [comment]
ok :)

**Comment by Ampretuzo** [comment]
Henrik, I implemented and tested this one with unit test, but I had to work around abstract validator.
It does not integrate with JSR-303 well and requires further type checkings in its implementations when multiple types need to be supported (in this case it is Date and Calendar classes).
There are two ways to do this task: (i) write with work arounds quickly to get things done, or (ii)  modify/change abstract validator class to comply with JSR nicely. I'll do (i) first, not to mess things up and only afterwards an issue should be made to fundamentally improve abstract validator.
I really need to sleep right now so I'll finish other two issues (#657, #655) tomorrow :)

**Comment by hendrikebbers** [comment]
Using the abstract class is not a must :) I think your idea sounds good 👍
