### ISSUE TITLE
Provide additional unit tests for ReflectionHelper

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#663]
Currently we do not have unit tests for most methods of this class

**Comment by h93xV2** [comment]
I am going to start working on this.

**Comment by hendrikebbers** [comment]
@h93xV2 👍

**Comment by h93xV2** [comment]
@hendrikebbers I am a little confused on how to run specific test classes. I tried to target `ReflectionHelperTest` with

`./gradlew test --tests ReflectionHelperTest`

and realized this was not the way to go about it. Do you have any hints for me?

**Comment by hendrikebbers** [comment]
you can simply do

`./gradlew :dolphin-platform-core:test`

this will start all tests in the dolphin-platform-core module. Since all the tests run < 1 sec that is the easiest way to do it.

**Comment by h93xV2** [comment]
Awesome, thanks. After reading the documentation I was starting to get closer to that, but your comment really helps.
