### ISSUE TITLE
(doc) Update release guide for changed Polymer client

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#673]
The release process for the new Polymer v2 client has changed a bit:

- [ ] Examples: we need to use `git add --all --force .` to add files from `bower_components` and `node_modules`. Otherwise it will not consider `dist/` directories (e.g. `bower_components/dolphin-platform-js/dist`) for the commit.
- [ ] Build: `gulp` was replaced with `polymer` cli command using `npm run build`.
- [ ] Build: Sonar was removed from the build process. Might be added back in the future.

Reference: https://canoo.github.io/dolphin-platform/#_major_release_of_the_dolphin_platform

**Comment by hendrikebbers** [comment]
@hastebrot can you maybe do this till next week? I need this when I do the next release

**Comment by hendrikebbers** [comment]
@hastebrot PING ;)

**Comment by hendrikebbers** [comment]
We have release scripts now.
