### ISSUE TITLE
Concurrency error in task executor for Dolphin Platform: Cause not logged

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#674]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
The following exception was found in a server log:

```
ERROR com.canoo.dp.impl.server.context.DolphinContextCommunicationHandler - Can not handle the the received commands (DolphinContext bcc430e2-e9e1-428c-b60f-62cbef8bb95f)

java.lang.IllegalStateException: Concurrency error in task executor for Dolphin Platform session bcc430e2-e9e1-428c-b60f-62cbef8bb95f
        at com.canoo.dp.impl.server.context.DolphinContextTaskQueue.executeTasks(DolphinContextTaskQueue.java:144)
        at com.canoo.dp.impl.server.context.DolphinContext.onPollEventBus(DolphinContext.java:303)
        at com.canoo.dp.impl.server.context.DolphinContext.access$1200(DolphinContext.java:69)
        at com.canoo.dp.impl.server.context.DolphinContext$4$6.call(DolphinContext.java:219)
        at com.canoo.dp.impl.server.context.DolphinContext$4$6.call(DolphinContext.java:212)
       ...
```

As you can see in the code of DolphinContextTaskQueue this exception is always based on a cause that is not added to log (stack trace / cause). This must be changed.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by hendrikebbers** [comment]
At first the cause should be logged! The error can be an application error
