### ISSUE TITLE
Add common HTTP status codes to HttpStatus and move interface to public API

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#695]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
The interface currently only contains 3 status codes. Other can easily be added. Once it provides a good list it should be moved to the public API.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by rahulp0491-fk** [comment]
I will claim this one !

**Comment by suryaprakashraja** [comment]
Hi @hendrikebbers , I would like to work on this issue. Moreover I would like to know which public API we need to move this interface? I hope core module is pubic so can we move there?

**Comment by hendrikebbers** [comment]
Public / private is not about the module but about the package. As you can see the modules have 2 main packages. ´com.canoo.platform´ is the base package for the public API

**Comment by kunsingh** [comment]
@hendrikebbers This is already done.

**Comment by hendrikebbers** [comment]
ok, will close it :)
