### ISSUE TITLE
Build of master is broken based on missing gradle dependency

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#710]
Looks like the build of the master branch is broken based on a missing dependency for the gradle build:

```
* What went wrong:
A problem occurred configuring root project 'dolphin-platform'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find license-gradle-plugin.jar (nl.javadude.gradle.plugins:license-gradle-plugin:0.11.0).
     Searched in the following locations:
         https://jcenter.bintray.com/nl/javadude/gradle/plugins/license-gradle-plugin/0.11.0/license-gradle-plugin-0.11.0.jar
```

This should be fixed asap ;)

**Comment by hendrikebbers** [comment]
See https://travis-ci.org/canoo/dolphin-platform/builds/294394104

**Comment by hastebrot** [comment]
The Gradle plugin jar is available on JCenter BinTray (the URL above). Strange.

**Comment by hendrikebbers** [comment]
Yes, checked this too. I restarted the master build. Let‘s see what happens ;)

Von meinem iPhone gesendet

**Comment by hendrikebbers** [comment]
Just broke once. Maybe a temporal problem to download the dependency...
