### ISSUE TITLE
Check ConverterFactory getTypeIdentifier & class type at start

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#711]
### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
If we have 2 same class types for conversion or 2 same unique identifiers the bootstrap should throw an exception. Instances of `com.canoo.platform.remoting.spi.converter.ConverterFactory` class are loaded by SPI.  See` com.canoo.dp.impl.remoting.Converters` class.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

### 🆕🐥:dog: First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

### :space_invader: Description of the issue
Currently the different modules of our samples (see `platform-examples` folder) are named different in the samples (`server`, `common`, `client`, ...). All modules should be renamed based on the modules in the `process-monitor-sample` sample.

### 📋 Step by Step
- 🙋 Claim this issue: Comment below.
- 🔄 replace the up for grabs label with in progress.
- :fork_and_knife: fork the repository in github by simply clicking the 'fork' button.
- :arrow_heading_down: check out the forked repository
- :twisted_rightwards_arrows: create a feature branch for the issue. We do not have any naming definition for branches.
- 💾 Commit your changes.
- 🔀 Start a Pull Request.
- 🏁 Done 👍 Ask in comments for a review :)
- 🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- :boom: you did it! We will merge the fix in the master of the Dolphin Platform project.
- :bouquet: Thanks, thanks, thanks for being part as an open source contributor for Dolphin Platform

### 🤔❓ Questions
You can [join our community chat at Slack](https://join-dolphin-platform-slack.herokuapp.com/)

**Comment by Ampretuzo** [comment]
I'll check this out tomorrow.

**Comment by mohamadLy** [comment]
I want to take this issue, if it hasn't been claim yet.

**Comment by kunsingh** [comment]
@mohamadLy Thanks for your interest. This issue is already resolved with some other issue and currently under review. No worry you can try other First Timer issues.

**Comment by kunsingh** [comment]
This is related to #778
