### ISSUE TITLE
ClientSessionExecutorImpl#callLaterinClientSession swallows Exceptions

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#737]
DP 0.19

If in the task.call() an Exception is thrown the exception (for example a NPE) we do give the future the exception, but then nothing more happens. The exception does for example not appear in the log and is silently ignored.

**Comment by blackdrag** [comment]
The test does not test the scenario I have a problem with. In my scenario nobody calls get(), thus no exception is thrown, which is exactly my problem. Additionally I have no control over the Future here, this is completely internally in Dolphin

**Comment by hendrikebbers** [comment]
@blackdrag so you would love to see a unhandled exception in that case in the log?

**Comment by blackdrag** [comment]
Having it at least in the log would be wonderful
