### ISSUE TITLE
Use shorter names and values for internal attributes

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#74]
To optimize the protocol, we should use shorter (single character?) names and values for our internal attributes

**Comment by Dierk** [comment]
This is very unfortunate for logging/debugging.
One can use the ZippedJsonCodec instead in production (or just use https, which zips anyway)

**Comment by netopyr** [comment]
I have worked with such protocols (e.g. FIX) and it is really no problem during development, because one learns and memorizes the important fields quickly. :) Optionally we could introduce a debug flag, which would switch to full names. But as I said, I do not deem that necessary.

Compressing data before encrypting it introduces new kinds of vulnerabilities, thus I would prefer if it remains optional and we try to get good performance without the need for compression.

**Comment by aalmiray** [comment]
Shortening command and attribute names sounds like a good idea to me. Having a flag that turns this feature on/off is also good. Further down the road, perhaps a BSON or binary YAML codecs can be created to make the payload even smaller.

**Comment by Dierk** [comment]
when I get log output from clients for answering support questions (dev/test/prod) it is of extreme value to see the full picture. 
This issue is to be handled at the codec level.

**Comment by aalmiray** [comment]
A delegating codec sounds like a good compromise to me

**Comment by hendrikebbers** [comment]
@Dierk Your idea is to create something like a FastJsonCodec class next to the normal one (JsonCodec) that uses smaller names for the attributes? If yes, I think that this can be done.

**Comment by Dierk** [comment]
there already is
https://github.com/canoo/open-dolphin/blob/3d7637b1ef5bfedc0cd43c1d5af5e924025011fa/subprojects/shared/src/main/groovy/org/opendolphin/core/comm/ZippedJsonCodec.groovy#L34-L34
