### ISSUE TITLE
deadlock in unit test when waiting for effect of callLaterInClientSession 

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#751]
DP 0.19.0

I have a controller setting a property value in a block executed with remotingContext.createSessionExecutor().callLaterInClientSession executed from the onInit of the controller. And I have a Unit test for that controller, which now has to wait for the property to be set. This seems to result in a deadlock

My wish would be for a way to wait till a certain property value is set, which should include dolphin to execute the blocks queued with callLaterInClientSession. I was also thinking of waiting for all such blocks to be done, but since such a block my enqueue a new such block this would again become untestable. Another alternative is to provide a kind of "iterator", that allows me to go through the callLaterInClientSession block execution, then I step through them till all the properties of interest are set

**Comment by hendrikebbers** [comment]
I added a sample application to DP that uses lazy loading
Next step will be controller tests.
See PR https://github.com/canoo/dolphin-platform/pull/753

**Comment by blackdrag** [comment]
from my test try:

        login("theUser");

        ControllerUnderTest<CaseSelectionBean> controller = createController(CONTROLLER_NAME);

        assertNotNull(controller);
        Property<String> casesProperty = controller.getModel().casesPropperty();
        AtomicReference<String> beforeSortString = new AtomicReference<>(null);
        CountDownLatch latch = new CountDownLatch(1);
        casesProperty.onChanged(evt -> {
            if (!isBlank(evt.getNewValue())) {
                beforeSortString.set(evt.getNewValue());
                latch.countDown();
            }
        });
        latch.await();

        JsonObject beforeSort = new JsonParser().parse(beforeSortString.get()).getAsJsonObject();
        assertEquals(beforeSort.size(), caseService.findAll().size());

        controller.invoke(SORT_CASES_ACTION,
            new Param(SORT_CASES_COLUMN_NAME_PARAM, "caseType"),
            new Param(SORT_CASES_DIRECTION_PARAM, ASC.direction));

        String afterSortString = controller.getModel().casesPropperty().get();
        assertNotEquals(afterSortString, beforeSortString);
