### ISSUE TITLE
Should we rename "Dolphin*" public API?

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#757]
DolphinEventBus -> RemotingEventBus
DolphinModel -> Model
DolphinController -> Controller
DolphinAction -> Action

**Comment by hendrikebbers** [comment]
Idea:

DolphinEventBus -> RemotingEventBus
DolphinModel -> RemotingModel
DolphinController -> RemotingController
DolphinAction -> RemotingAction

@blackdrag what do you thing

**Comment by kunsingh** [comment]
@madmas @blackdrag @netopyr @timo0 What you guys think?

**Comment by netopyr** [comment]
I don't have much of an opinion.

**Comment by blackdrag** [comment]
The variant with Remoting in front looks better to me than the other one. But I wonder if it is good to rename at all.

**Comment by madmas** [comment]
I think it looks and fits better, too. Renaming should IMHO definetly be done before the 1.0 release ;-)

**Comment by hendrikebbers** [comment]
Some more information:

@madmas That's why I want to do it NOW ;)
@blackdrag Since the DP is growing and we have more modules and functionalities next to the remoting layer a name like `DolphinModel` is to generic. Maybe we have another feature / module where we need a general module class / definition. If we than name this by the feature (like `ValidationModel` for example) we would have one class (`DolphinModel`) that do not match the pattern. Based on that it makes sense to rename it directly and use the module / functionality as a prefix.

**Comment by blackdrag** [comment]
If 'DolphinModel' is too general, then just 'Model' is even more general. I guess that eliminates this Variant. Then go with the 'Remoting'-prefix

**Comment by timo0** [comment]
sounds like a may search and replace actions ;-)
