### ISSUE TITLE
Keycloak security 

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#782]
It would be very helpful if there would be an example how to integrate dolphin-security and how to configure keycloak for that. 

For me authentification with keycloak only works if I disable dolphin-security on the server part of my app. For example commenting out @EnableSecurity. My javafx-client uses this code:

```
public static void main(String[] args) {
       Platform.setImplicitExit(false);
       PlatformClient.getClientConfiguration().setStringProperty(SecurityConfiguration.APP_NAME, “kickstart”);
       PlatformClient.getClientConfiguration().setStringProperty(SecurityConfiguration.AUTH_ENDPOINT, “http://localhost:8080“);
       PlatformClient.getClientConfiguration().setStringProperty(SecurityConfiguration.REALM_NAME, “Wuerth”);
       Application.launch(args);
   }
```

This code is in the java-fx-Client (with server dolphin-security disabled) and works:

```
final Security security = PlatformClient.getService(Security.class);
           System.out.println(“security.isAuthorized() before auth: ” + security.isAuthorized());
           Future<Void> future = security.login(“kurt.meier”, “kurt”);
           try {
               future.get();
               System.out.println(“security.isAuthorized() after auth: ” + security.isAuthorized());
           } catch (InterruptedException e) {
               e.printStackTrace();
           } catch (ExecutionException e) {
               e.printStackTrace();
           }
```

BUT, if I enable dolphin-security on the server, then the client auth dont work anymore and I get this messages on the client:

Dolphin-Platform-Background-Thread-0] DEBUG com.canoo.dp.impl.remoting.codec.OptimizedJsonCodec - Encoding command list with 1 commands
[Dolphin-Platform-Background-Thread-0] DEBUG com.canoo.dp.impl.platform.client.http.cookie.HttpClientCookieHandler - adding cookies from cookie store to request
[Dolphin-Platform-Background-Thread-0] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionStoreImpl - searching for client id application domain: localhost:8666
[Dolphin-Platform-Background-Thread-0] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionStoreImpl - found client id ‘null’ for application domain localhost:8666
[Dolphin-Platform-Background-Thread-0] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionRequestHandler - Request to application at http://localhost:8666/todo-app/dolphin without client id. PlatformClient id not defined until now.
[Dolphin-Platform-Background-Thread-1] DEBUG com.canoo.dp.impl.platform.client.http.cookie.HttpClientCookieHandler - adding cookies from response to cookie store
[Dolphin-Platform-Background-Thread-1] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionStoreImpl - updating client id for application domain: localhost:8080
[Dolphin-Platform-Background-Thread-1] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionStoreImpl - Defining client id ‘null’ for application domain localhost:8080
[Dolphin-Platform-Background-Thread-1] DEBUG com.canoo.dp.impl.platform.client.session.ClientSessionStoreImpl - Since client id for application domain localhost:8080 is defined as ‘null’ it will be removed
[JavaFX Application Thread] ERROR com.canoo.platform.remoting.client.javafx.DolphinPlatformApplication - Dolphin Platform initialization error
com.canoo.platform.remoting.client.ClientInitializationException: Can not initialize Dolphin Platform Context
    at com.canoo.platform.remoting.client.javafx.DolphinPlatformApplication.init(DolphinPlatformApplication.java:128)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at com.canoo.platform.remoting.client.javafx.DolphinPlatformApplication.init(DolphinPlatformApplication.java:124)
    ... 3 more
[Dolphin-Platform-Background-Thread-0] ERROR com.canoo.dp.impl.platform.core.SimpleUncaughtExceptionHandler - Unhandled error in Dolphin Platform background thread Dolphin-Platform-Background-Thread-0
java.lang.IllegalStateException: Connection is broken
    at com.canoo.dp.impl.client.legacy.communication.AbstractClientConnector.send(AbstractClientConnector.java:150)
    at com.canoo.dp.impl.client.legacy.communication.AbstractClientConnector.send(AbstractClientConnector.java:162)
    at com.canoo.dp.impl.client.DolphinCommandHandler.invokeDolphinCommand(DolphinCommandHandler.java:40)
    at com.canoo.dp.impl.client.ClientContextImpl$2.run(ClientContextImpl.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by hendrikebbers** [comment]
@joha78 maybe you can have a look at the PR if this fits your needs
