### ISSUE TITLE
spring-boot-archetype needs to be updated

### ISSUE THREAD

**Issue by jermsam** [canoo/dolphin-platform#788]
Good Work DP Team: Still finding it hard to jumpstart a dp 0.19.0 (or later) project though.

Noticed that The cmd; mvn archetype:generate -Dfilter=com.canoo.dolphin-platform: gives only versions for the spring-boot-archetype from 0.16.0 and earlier

Tried using 0.16.0 spring-boot-archetype and edited version to 0.19.0 then updated dependencies
but got errors that 0.19.0 dependencies are not available for all modules(client,common and server)
tried starting from the samples in the repository whose link you sent me but all are of gradle.

**Comment by kunsingh** [comment]
Done.

**Comment by jermsam** [comment]
Finally! Thanks Team.
