### ISSUE TITLE
add final keyword to generated code of intelliJ plugin

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#802]
Example:

```
public void setLoggerName(final String loggerName) {
        this.loggerName.set(loggerName);
    }
```

**Comment by timo0** [comment]
This is a setting in IntelliJ please see attached screen shot:
![screen shot](https://user-images.githubusercontent.com/1241026/34727351-ef521596-f556-11e7-822c-09ab0dc0ee77.png)
