### ISSUE TITLE
Use Web Workers to do the AJAX work in another Thread

### ISSUE THREAD

**Issue by giftkugel** [canoo/dolphin-platform#825]
I think it would be quite good to move the AJAX related work into a Web Worker. So the `LongPoll` Command and the other Commands could be send and received by a separate Thread inside the Browser.

Web Works are supported down to IE10.
[Can I use Web Workers](https://caniuse.com/#feat=webworkers)
[Worker() @ MDN](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker)

I would prefer to use a BLOB URL to load a Script into the Web Worker. BLOB URL can be used down to IE10 too.
[Can I use Blob URL](https://caniuse.com/#feat=bloburls)
[URL.createObjectURL() @ MDN](https://developer.mozilla.org/de/docs/Web/API/URL/createObjectURL)

**Comment by giftkugel** [comment]
Any opinion to this topic from @blackdrag @kunsingh @Dierk @madmas @timo0 ?

**Comment by Dierk** [comment]
Will be difficult to get the command batcher to work ...

Dierk

sent from:mobile

**Comment by hendrikebbers** [comment]
@Dierk why do you think that? In Java there were 2 threads since the beginning. The command batcher is only attached to the basic thread that handles all the normal commands since the second thread is only used for interrupting the long poll.

**Comment by giftkugel** [comment]
The JavaScript client now contains an implementation of a HTTP Client (#609) which is used in the remoting part of the JavaScript client.
The HTTP Client supports the usage of Web Workers but will only use a Web Worker if the current Browser supports Web Workers. The Web Worker is bundle inside the JavaScript client, so we don't have to provide another JS file.
At the moment only a single LongPoll command will be send through the Web Worker. Can be changed in the feature.
