### ISSUE TITLE
Polymer 2 "dolphin-controller" element is missing listener for lifecycle

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#836]
With the Polymer 1 support is was quite easy to define methods that were called when the controller proxy was created or destroyed. Since with Polymer 2 we now have a custom component this functionality is missing.

I would say that something like this should work:

```
<dom-module id="detail-view">
    <template>
        <dolphin-controller onConnected="_onConnected()" onDisconnected="_onDisconnected()">
        </dolphin-controller>
    </template>
    <script>
        HTMLImports.whenReady(function() {
            Polymer({
                is: 'detail-view',
                _onConnected() {......},
                _onDisconnected() {......},
            });
        });
    </script>
</dom-module>
```

If there is a better option to define such API feel free to describe it :) For me it is just important that I can react on connection

**Comment by hendrikebbers** [comment]
[sample.zip](https://github.com/canoo/dolphin-platform/files/1676852/sample.zip)
Sample project that contains the problem

**Comment by hastebrot** [comment]
Related to https://github.com/canoo/dolphin-platform-polymer/pull/18.

**Comment by giftkugel** [comment]
With the new controller it's possible to receive the events for connect and disconnect. `<remoting-controller on-connect="methodName" on-disconnect="othermethodName"></remoting-controller>`
