### ISSUE TITLE
Dolphin-Controller Polymer 2 componente do not update all model parts

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#837]
In a sample I checked the update behaviour of models in the new polymer component and found some cases in that model updates do not trigger polymer. Based on that the view is not updated.

**Comment by hendrikebbers** [comment]
[sample.zip](https://github.com/canoo/dolphin-platform/files/1676854/sample.zip)
Sample project that contains the problem

**Comment by hastebrot** [comment]
I'll look into that.

**Comment by hastebrot** [comment]
The `model` in `<workbench-view>` is `{}`.

**Comment by hendrikebbers** [comment]
no,the problem is in `detail-view`

**Comment by hastebrot** [comment]
The `<app-router>` (https://github.com/erikringsmuth/app-router) in `<workbench-view>` also causes problems unrelated to `<dolphin-controller>`.

**Comment by hastebrot** [comment]
In `detail-view.html`

~~~
ready() {
  setTimeout(() => {
    console.log(JSON.stringify(this.$.controller.model))
  }, 500)
},
~~~

will give me `{"name":"","description":"","id":null}`.

**Comment by hastebrot** [comment]
When I manually set `this.id = 1` in `ready()`, then `this.$.controller.model` will be `{"name":"TestValue","description":"Die ist die Beschreibung für Item 1...","id":1}`.

**Comment by hastebrot** [comment]
This is strange and needs more investigation.

In `dolphin-controller.html`:

~~~
      _onBeanPropertyChanged(bean, propertyName, newValue, oldValue) {
        // TODO(hastebrot): Maybe use bean[propertyName] instead of oldValue?
        if (isEqual(newValue, oldValue)) { return }

        if (this.model) {
          this.model.description = "foo"
        }
~~~

Will cause the `model.description` property to be updated to the values mentioned above. I guess one of the explicit notifications for property changes to Polymer failed somehow.

**Comment by hendrikebbers** [comment]
@hastebrot 
```
TypeError: e.registerElement is not a function
http://localhost:8000/bower_components/app-router/app-router.html.js:2:4382
http://localhost:8000/bower_components/app-router/app-router.html.js:2:2
```

^^This error was not shown in my Chrome.

To see the problem: Open the client and click on any item in the list. Then you see the detail-view and only the `ID` is shown the the view. `Name` and `description` is empty. I debugged this and saw that the values in the `model` item of the `dolphin-controller` component are not `null`. The problem is in the `dolphin-controller` component. The listener that is registered to the original dolphin model do not update all changes to polymer.

```
code snippet from `dolphin-controller.html`:

_onBeanPropertyChanged(bean, propertyName, newValue, oldValue) {
        if (isEqual(newValue, oldValue)) { return }
        const propertyPaths = this._queryPropertyPaths(bean)
        if (propertyPaths.size > 0) {
          const parentPropertyPath = Array.from(propertyPaths)[0]
          const propertyPath = this._buildPropertyPath(parentPropertyPath, propertyName)
          this.set(propertyPath, newValue)
        }
        else {
          bean[propertyName] = newValue
        }
      }
```

Sometimes the `else` case will be handled. And this one do not update the polymer model.

**Comment by hastebrot** [comment]
In my case the `if` case is handled at least one time with `propertyPath = "model.description"` and `newValue` with a non-empty string. However `this.set()` does not cause the properties in the Polymer template to be updated, despite `description` in `model` set to a non-empty string.

**Comment by hastebrot** [comment]
Problem identified.
The `dolphin-controller>`s in `detail-view.html` and `workbench-view.html` share one bean manager. This will cause the callback to be called twice.

~~~
_onClientContextChanged() {
  if (isNil(this.clientContext)) { return }

  this._beanManager = this.clientContext.beanManager
  this._beanManager.onBeanUpdate(this._onBeanPropertyChanged.bind(this))
  this._beanManager.onArrayUpdate(this._onBeanPropertySpliced.bind(this))
}
~~~

**Comment by jermsam** [comment]
then, what's the solution @hastebrot ?

**Comment by hastebrot** [comment]
@jermsam Best solution is to add a feature to `dolphin-platform-js` that gives us the bean manager for a certain controller. Still needs to be implemented.

~~~js
// before:
this._beanManager = this.clientContext.beanManager

// after:
this._beanManager = this.clientContext.getBeanManagerForController(this.name)
~~~

**Comment by hastebrot** [comment]
This needs to be investigated further. I want to reproduce this issue with the DP Polymer v1 client.

**Comment by hastebrot** [comment]
Console output for Polymer v1 client (using modified `dolphin-platform-polymer.js`):

~~~js
Binder.prototype.onBeanUpdateHandler = function(bean, propertyName, newValue, oldValue) {
    console.log("->", propertyName, newValue, JSON.stringify(bean))
~~~

~~~
-> name  {"name":null,"description":null,"id":null}
-> description  {"name":"","description":null,"id":null}
-> id 1 {"name":"","description":"","id":1}
-> name Item 1 {"name":"","description":"","id":1}
-> description Die ist die Beschreibung für Item 1... {"name":"Item 1","description":"","id":1}
-> name TestValue {"name":"TestValue","description":"Die ist die Beschreibung für Item 1...","id":1}
~~~

Console output for Polymer v2 client (using modified `dolphin-controller.html`):

~~~js
_onBeanPropertyChanged(bean, propertyName, newValue, oldValue) {
  console.log("->", propertyName, newValue, JSON.stringify(bean))
~~~

~~~
-> name  {"name":null,"description":null,"id":null}
-> name  {"name":"","description":null,"id":null}
-> description  {"name":"","description":null,"id":null}
-> description  {"name":"","description":"","id":null}
-> id 1 {"name":"","description":"","id":1}
-> name Item 1 {"name":"","description":"","id":1}
-> name Item 1 {"name":"Item 1","description":"","id":1}
-> description Die ist die Beschreibung für Item 1... {"name":"Item 1","description":"","id":1}
-> description Die ist die Beschreibung für Item 1... {"name":"Item 1","description":"Die ist die Beschreibung für Item 1...","id":1}
-> name TestValue {"name":"TestValue","description":"Die ist die Beschreibung für Item 1...","id":1}
~~~

**Comment by hastebrot** [comment]
More console output (using modified `dolphin-platform-polymer.js`):

~~~js
function setupCreateBehavior(clientContext) {
    console.log("-> create binder")

    var binder = new Binder(clientContext.beanManager);

    return function(controllerName) {
        console.log("-> create controller:", controllerName)
~~~

~~~
-> create binder
-> create controller: DetailController
-> create controller: WorkbenchController
~~~

**Comment by hendrikebbers** [comment]
@hastebrot Together with @giftkugel we found a working solution. He has already created a fix for the Polymer repo and will create a PR at the beginning of next week. So I think you do not need to invest time here at the moment. Sorry, missed to add this to the issue.

**Comment by hastebrot** [comment]
For the record: In the Polymer v1 client we use one `Binder` per `BeanManager`/`ClientContext. The update handlers call `element.set()` and `element.splice()`, respectively. This means the "bean registry" also has to register the Polymer `element` in order to call these methods.

**Comment by hendrikebbers** [comment]
@hastebrot sorry but I do not understand what you want to say :( Do you see any problem? Bug in Polymer 1 support? Missing feature in Polymer 2 support?

**Comment by giftkugel** [comment]
The problem does not exist in the new version of the controller. The example is working right now with the `<remoting-controller>`.
