### ISSUE TITLE
Remove "bower install --force-latest"

### ISSUE THREAD

**Issue by giftkugel** [canoo/dolphin-platform#855]
We have to remove `bower install --force-latest` from the build (`.travis.yml`).
I think the "--force-latest" option was used here to resolve version conflicts and to force Bower to use the latest version. Be in that case we don't know which version will be used in the build. We have to remove the option and resolve the correct version in the `bower.json` with the "resolutions" block.

[https://jaketrent.com/post/bower-resolutions/](https://jaketrent.com/post/bower-resolutions/)

**Comment by kunsingh** [comment]
Fixed.
