### ISSUE TITLE
Service provider with same name in dolphin-platform-client and dolphin-platform-remoting-client

### ISSUE THREAD

**Issue by kunsingh** [canoo/dolphin-platform#861]
This is creating problem while creating jar of client. It copies only first occurrence from dolphin-platform-remoting-client and it has only entry for 'com.canoo.dp.impl.client.ClientContextFactoryProvider'

Calling javafx client through jnlp is failing due to this.

This will also fix - https://github.com/canoo/dolphin-platform/issues/475

**Comment by hendrikebbers** [comment]
This is not an error / Problem of the framework but just of the app build. The SPI filed must be merged at buildtime if you pack everything in a fat jar. Since SPI is a standard there will be several samples online. This issue can be closed 

Von meinem iPhone gesendet

**Comment by kunsingh** [comment]
ok...I will close this issue.
