### ISSUE TITLE
Keycloak unavailable undistinguishable from "Invalid login!"

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#894]
This is not really an issue, but in the client it is not distinguishable whether 

security.login(user, password) 

failed because the keycloak server is down or because the password was wrong because both cases report the same Exception / message.

**Comment by hendrikebbers** [comment]
An invalid Login currently throws `DolphinRuntimeException("Invalid login!")` and a not reachable server will end in an DolphinRuntimeException with a different message. Yes, I think it makes sense to create a new exception type. Both Java & Spring already define a `AuthenticationException` so I think we should use a different name.

**Comment by hendrikebbers** [comment]
This issue was moved to rico-project/rico#9
