### ISSUE TITLE
ObserveableList.remove(from,to) is broken

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#901]
using Dolphin Platform 1.0-CR3 I have the following situation:
* ObservableList of size 5
* calling remove(0,3) on it
* get :

   java.lang.IndexOutOfBoundsException: toIndex = 3

	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at com.canoo.dp.impl.remoting.collections.ObservableArrayList.subList(ObservableArrayList.java:283)
	at com.canoo.dp.impl.remoting.collections.ListMapperImpl.processEvent(ListMapperImpl.java:102)
	at com.canoo.dp.impl.server.model.ServerBeanBuilderImpl$1.notifyInternalListeners(ServerBeanBuilderImpl.java:69)
	at com.canoo.dp.impl.remoting.collections.ObservableArrayList.fireListChanged(ObservableArrayList.java:60)
	at com.canoo.dp.impl.remoting.collections.ObservableArrayList.remove(ObservableArrayList.java:258)

looking a bit at the code the obvious problem seems to be in ListMapperImpl.processEvent. To process the remove we first mutate the list (result list has size 2) and store from:0, to:3 and the sublist of removed elements in a change, that is available in the event given to processEvent. But processEvent tries to sublist(0,3) the original list, which has already been mutated, instead of just taking the already existing list from the ChangeImpl. Since the mutated list is of size 2, a sublist 0,3 fails of course with the exception above.

**Comment by blackdrag** [comment]
I spend no extensive look at master, but the code in ListMapperImpl.processEvent looks the same, so I assume this problem exists in Master as well

**Comment by kunsingh** [comment]
I have tried with a simple test...and I have not get any exception. Am I missing something in below code?
`

    public void testRemoveByIndexPositions() {
        //given
        final ObservableArrayList<String> list = new ObservableArrayList<>();
        list.addAll("1", "2", "3", "4", "5");
        list.remove(0,3);
        Assert.assertEquals(list.size(), 2);
    }
`

**Comment by hendrikebbers** [comment]
@kunsingh good question. Can you please commit this as a unit test :)

@blackdrag looks like it is working in a basic tests. Do you have more info?

**Comment by blackdrag** [comment]
I don't think you get to 

com.canoo.dp.impl.server.model.ServerBeanBuilderImpl$1.notifyInternalListeners(ServerBeanBuilderImpl.java:69)

with that test. or do you?

**Comment by blackdrag** [comment]
ObservableArrayList#notifyInternalListeners is an empty protected method, so I think we are actually working on a subclass of this. So maybe try the test again involving ServerBeanBuilderImpl#create(PropertyInfo,PresentationModel,ListMapper)
