### ISSUE TITLE
(feature) Polymer: Remoting controller for Polymer 3.

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#908]
Google will release Polymer 3 at Google I/O 2018 this week (conference sessions on May 9th). With Polymer 3 we'll still have the option to use `<remoting-controller>` as mixin for `PolymerElement`. But the stated goal of the Polymer team it to allow lighter and more loosely coupled elements, hence they'll introduce `LitElement` (headed for 1.0 release in the coming months). This new Web Component base class will be the successor of `PolymerElement`.

To support `PolymerElement` in Polymer 3 we probably have to additionally provide `<remoting-controller>` on npm registry. It would also be nice if the element is converted to JavaScript modules, though still using HTML imports should still be fine. The `PolymerElement` will not see active development in the future.

To support `LitElement` in Polymer 3 we'd have to rethink how Dolphin Platform communicates changes to this base class. It will get rid of the Polymer data system and template stamping (no property effects with `set()` and `splice()`, no templates with two-way bindings). The Polymer team suggests to use Redux state store instead, but also says with `LitElement` you should be free for more different options.

**Comment by hastebrot** [comment]
Regarding `LitElement`, `lit-html`, and redux stores. I played a bit with Dolphin Platform and found following obstacles:

- **Dolphin ▶️ redux ▶️ `LitElement`:** Using the Dolphin's approach to identify beans by object reference and redux's nature (freeze'd objects) give some obstacles. Redux has the concept of selectors (see: `reselect` [1]) which could be helpful to specify changes/splices to bean properties). `LitElement` uses `lit-html` which takes the complete property tree (say: Dolphin `model`) and only update the template parts that causes changes, i.e. only applies the subproperties that causes these changes.

- **`LitElement` ▶️ redux ▶️ Dolphin:** Here we probably need to diff the objects, to explictly send the changes to the Dolphin controller. The `immer` library [2] could be helpful, if it allow to retrieve a list of changed subproperties.

Additionally how to mix uni-directional changes (the `LitElement`/redux appoach) and bi-directional changes (the `PolymerElement` approach) is an open question.

References:
- [1] https://github.com/reduxjs/reselect
- [2] https://github.com/mweststrate/immer

**Comment by hendrikebbers** [comment]
This issue was moved to rico-project/rico#7

**Comment by hendrikebbers** [comment]
This issue was moved to rico-project/rico#11
