### ISSUE TITLE
In JavaScript client: Model modifications will be received in the wrong Controller?

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#912]
Aktuellste Version mit "dynamische (client managed) Realm" aktiviert.

Wenn vom Server etwas vom Client gesendet wird, dann kommt es im Client in der falschen View raus.

Das führt zu solchen Meldungen:
2018-05-28 01:48:33.766 [ERROR] RemotingController MAIN_VIEW_CONTROLLER Bean not found in model! {destinationCity: “Rom”, departureCity: “Hamburg”, …..

Das Merkwürdige daran, die Daten die angeblich in MAIN_VIEW_CONTROLLER landen sollen, sind tatsächlich für eine ganz andere View, also einen ganz anderen Controller, bestimmt.

Der Controller hat ja ein init(), welches Model-Modifikationen an den Client weitergibt. Da ist noch alles ok. Wenn ich dann aber später etwas sende, z.B aus einer Server-Action heraus, dann kommt es im Client nicht mehr an der richtigen Stelle an.

**Comment by hendrikebbers** [comment]
This issue was moved to rico-project/rico#2
